### PR TITLE
Fix #7: removed div element and added pagination class to ul/ol element

### LINKED ISSUE #7: Bootstrap pagination
Hello,

It appear that the `pagination` class is applied to the `div` element
However, to be bootstrap-compliant, it seems that it should be applied to the `ul`: http://getbootstrap.com/components/#pagination

### PR DESCRIPTION
**Pull request by jackmakiyama**
Fixed issue #7.

### CODE REVIEW

**Comment by deanc** [comment]
C'mon @mardix merge this in :)

**Comment by jackmakiyama** [comment]
:+1: @deanc

**Comment by mardix** [comment]
Thank you. I'm looking into right now, and it will be soon merged.

**Comment by deanc** [comment]
Great to hear, looking forward to this so I can switch from using my own fork.

**Comment by deanc** [comment]
@mardix ;-)? Really would be nice to get this merged so I can switch deps to not using a fork.

**Comment by mardix** [comment]
Thank you very much. This has been moved to master.

**Comment by mardix** [comment]
Thank you @jackmakiyama for the update :100: 
Thank you @deanc for keeping on reminding me :+1:

**Pull request merged**
